valor1 = int(input("digite o primeiro valor:"))
valor2 = int(input("digite o segundo valor:"))
valor3 = int(input("digite o terceiro valor:"))
valor4 = int(input("digite o quarto valor:"))
valor5 = int(input("digite o quinto valor:"))
menorvalor = min(valor1, valor2, valor3, valor4, valor5)
maiorvalor = max(valor1, valor2, valor3, valor4, valor5)
print("o menor valor é:", menorvalor)
print("o maior valor é:", maiorvalor)